# Generated by Django 5.1.6 on 2025-03-21 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['day']},
        ),
        migrations.AlterModelOptions(
            name='matchday',
            options={'ordering': ['day_number']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['team_name']},
        ),
        migrations.AlterField(
            model_name='league',
            name='league_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_away',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_home',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchday',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_days', to='matches.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_name',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
