# Generated by Django 5.1.7 on 2025-03-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_options_alter_matchday_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['day', 'match_date']},
        ),
    ]
