# Generated by Django 5.1.6 on 2025-03-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_team_team_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date', 'day']},
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
