# Generated by Django 5.1.6 on 2025-05-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0007_league_season_match_season_team_season"),
    ]

    operations = []
