# Generated by Django 5.1.6 on 2025-05-07 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0008_restructure_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="league",
            options={"ordering": ["country", "league_name"]},
        ),
        migrations.AlterModelOptions(
            name="season",
            options={"ordering": ["-start_date"]},
        ),
        migrations.RemoveField(
            model_name="league",
            name="season",
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("match_date", "team_home", "team_away")},
        ),
        migrations.RemoveField(
            model_name="team",
            name="season",
        ),
        migrations.AddField(
            model_name="league",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="league",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/leagues/"),
        ),
        migrations.AddField(
            model_name="match",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="xG_away",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="xG_home",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="matches.league",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/teams/"),
        ),
        migrations.AlterField(
            model_name="match",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="matches.matchday",
            ),
        ),
        migrations.CreateModel(
            name="LeagueSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="matches.league",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leagues",
                        to="matches.season",
                    ),
                ),
            ],
            options={
                "unique_together": {("league", "season")},
            },
        ),
        migrations.AddField(
            model_name="matchday",
            name="league_season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_days",
                to="matches.leagueseason",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchday",
            unique_together={("day_number", "league_season")},
        ),
        migrations.RemoveField(
            model_name="match",
            name="league",
        ),
        migrations.RemoveField(
            model_name="match",
            name="referee",
        ),
        migrations.RemoveField(
            model_name="match",
            name="season",
        ),
        migrations.RemoveField(
            model_name="match",
            name="venue",
        ),
        migrations.RemoveField(
            model_name="matchday",
            name="season",
        ),
        migrations.CreateModel(
            name="TeamSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "league_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="matches.leagueseason",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="matches.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "league_season")},
            },
        ),
    ]
